// label/src/components/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { BRAND, webLogin } from '../api'
const code = ref('')
const error = ref('')
const busy = ref(false)
async function submit() {
  if (busy.value || code.value.length !== 6) return
  busy.value = true
  error.value = ''
  try { await webLogin(code.value) } catch (err) {
    error.value = err instanceof Error ? err.message : '登入失敗'
  } finally { busy.value = false }
}
</script>

<template>
  <div class="login">
    <form class="ds-card" @submit.prevent="submit">
      <h1>{{ BRAND }}</h1><p>建立模板</p>
      <label for="code">登入碼</label>
      <input id="code" class="ds-input code" inputmode="numeric" autocomplete="one-time-code"
        maxlength="6" placeholder="000000" autofocus :value="code"
        @input="code = ($event.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, 6)" />
      <p class="error" role="alert">{{ error }}</p>
      <button class="ds-btn ds-btn--primary" :disabled="code.length !== 6 || busy">{{ busy ? '登入中…' : '登入' }}</button>
      <p>在手機 App 的「設定 → 在電腦上看報告」取得 6 位數登入碼。</p>
    </form>
  </div>
</template>

<style scoped>
.login { min-height: 75vh; display: grid; place-items: center; padding: 20px; }
form { width: min(380px, 100%); padding: 32px 28px; display: flex; flex-direction: column; gap: 10px; }
h1 { font-weight: 700; text-align: center; }
.code { font-size: 32px; letter-spacing: .35em; text-align: center; }
p { font-size: 13px; color: var(--text-2); }
.error { min-height: 20px; color: var(--danger); }
</style>

// web/src/Login.tsx
import { useState } from "react";
import { webLogin } from "./api";

export default function Login({ onDone }: { onDone: () => void }) {
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      await webLogin(code);
      onDone();
    } catch (err) {
      setError(err instanceof Error ? err.message : "登入失敗");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="login">
      <form className="card" onSubmit={submit}>
        <div className="logo" style={{ fontSize: 26 }}>浮島</div>
        <div className="sub" style={{ marginTop: 6 }}>班級報告</div>
        <input
          id="code"
          className="code"
          inputMode="numeric"
          autoComplete="one-time-code"
          maxLength={6}
          placeholder="000000"
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
          aria-label="登入碼"
          autoFocus
        />
        <div className="err">{error}</div>
        <button className="primary" disabled={code.length !== 6 || busy}>{busy ? "登入中…" : "登入"}</button>
        <p className="note">在手機 App 的「設定 → 在電腦上看報告」取得 6 位數登入碼。</p>
      </form>
    </div>
  );
}
